### ISSUE TITLE
Lab DAM&SD - Use Case Diagram

### ISSUE THREAD

**Issue by visajshah** [visajshah/Grp22-Time-for-a-Break#7]

**Comment by adityashah44** [comment]
Should we include the new user use case?

**Comment by meetparmar002** [comment]
We should try to obtain details through Google Form.

**Comment by adityashah44** [comment]
Also, we can include a function that provides credentials for authentication

**Comment by adityashah44** [comment]
![LabIVLISusecase](https://user-images.githubusercontent.com/80560977/113475395-14807b80-9493-11eb-9c1a-4f84565216c4.png)
If this is fine then I'll be closing the issue with this diagram

**Comment by meetparmar002** [comment]
Looks fine to me.

**Comment by M23102000** [comment]
is the direction of extend fine?

**Comment by M23102000** [comment]
or should it be reversed?

**Comment by meetparmar002** [comment]
Yeah, It should be in the reverse direction.

**Comment by adityashah44** [comment]
Done

**Comment by adityashah44** [comment]
Any other issue?
