### ISSUE TITLE
Lab DAM&SD - Use Case Documentation for issueBook()

### ISSUE THREAD

**Issue by visajshah** [visajshah/Grp22-Time-for-a-Break#8]

**Comment by vyommodi03** [comment]
in our system first user will login with his account right?

**Comment by visajshah** [comment]
> in our system first user will login with his account right?

Yes. They need to enter their credentials. Once verified, they can log in.

**Comment by vyommodi03** [comment]
> > in our system first user will login with his account right?
> 
> Yes. They need to enter their credentials. Once verified, they can log in.
okay

**Comment by visajshah** [comment]
Should we mention how the status of the book is checked before it is issued?

**Comment by vyommodi03** [comment]
> Should we mention how the status of the book is checked before it is issued?

Yes ,First librarian will check the status of the book before issue the book and If it is available then it will assign.

**Comment by vyommodi03** [comment]
I think we should also include cases about new users.

**Comment by visajshah** [comment]
> I think we should also include cases about new users.

Okay, I will include this case in the documentation. We can talk about how the new users can have their accounts activated.

**Comment by vyommodi03** [comment]
should we include any maximum limit for users to issue books?

**Comment by visajshah** [comment]
> should we include any maximum limit for users to issue books?

Nothing regarding this is mentioned in the document sir has shared so we can avoid that.

**Comment by visajshah** [comment]
Documentation Draft: https://docs.google.com/document/d/1NgRU3JZi6Tt8oo_gigzhfTLj4vMw5rx2-F1M26UttsA/edit?usp=sharing

Anything else to add? Any changes?

**Comment by vyommodi03** [comment]
> Documentation Draft: https://docs.google.com/document/d/1NgRU3JZi6Tt8oo_gigzhfTLj4vMw5rx2-F1M26UttsA/edit?usp=sharing
> 
> Anything else to add? Any changes?

No, I think it's fine.
